version: "3.7"

services:
    database_ignite:
      image: login_postgres
      container_name: login_postgres
      restart: always
      ports:
        - 5432:5432
      environment: 
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=login_postgres
      volumes: 
        - pgdata:/data/login_postgres
    app:
      build: .
      container_name: login_postgres
      ports:
        - "5555:5555"
      volumes:
        - .:/usr/app

volumes:
    pgdata:
      driver: local